version: '3.8'

services:
  menumanager:
    image: ghcr.io/buadvdev2024/menumanager/menumanager-image:latest
    build:
      context: ./MenuManager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - HOST=0.0.0.0
      - PORT=8080
    stop_signal: SIGINT
    volumes:
      - ./MenuManager/src:/src
    networks:
      - pizza-network

networks:
  pizza-network:
    name: pizza-network
    driver: bridge