version: '3.8'

services:
  menumanager:
    image: ghcr.io/buadvdev2024/menumanager/menumanager-image:latest
    build:
      context: ./MenuManager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - HOST=0.0.0.0
      - PORT=8080
    stop_signal: SIGINT
    volumes:
      - ./MenuManager/src:/src
    networks:
      - shared-network

  ordermanagementsystem:
    image: ghcr.io/buadvdev2024/order-management-system:main
    build:
      context: ./Order-Management-System
      dockerfile: Dockerfile
    env_file:
      - ./Order-Management-System/.env
    volumes:
      - ./Order-Management-System:/app
    ports:
      - "5002:5002"
    command: ["gunicorn", "--bind", "0.0.0.0:5002", "app.main:app"]
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network
    driver: bridge