version: '3.8'

services:
  ordermanagementsystem:
    image: ghcr.io/buadvdev2024/order-management-system:main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5002:5002"
    command: ["gunicorn", "--bind", "0.0.0.0:5002", "app.main:app"]
    networks:
      - shared-network

networks:
  shared-network:
    external: true